# Generated by Django 4.2.2 on 2023-06-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
