# Generated by Django 4.2.2 on 2023-06-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predict', '0003_chatmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='link',
            field=models.SlugField(blank=True),
        ),
    ]
