# Generated by Django 4.2.2 on 2023-06-26 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profilemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female')]),
        ),
    ]
