# Generated by Django 4.2.2 on 2023-06-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_profilemodel_age_alter_profilemodel_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='link',
            field=models.SlugField(blank=True),
        ),
    ]
