# Generated by Django 4.2.2 on 2023-07-13 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_profilemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (0, 'Female')], null=True),
        ),
    ]
