# Generated by Django 4.2.2 on 2023-06-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DesignModel',
            new_name='DataModel',
        ),
    ]
