# Generated by Django 4.2.2 on 2023-06-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseAPI', '0003_remove_datamodel_title_datamodel_ca_datamodel_chol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='oldpeak',
            field=models.FloatField(null=True),
        ),
    ]
