# Generated by Django 4.2.2 on 2023-06-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseAPI', '0004_alter_datamodel_oldpeak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamodel',
            old_name='slope',
            new_name='slop',
        ),
    ]
