# Generated by Django 4.2.2 on 2023-07-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseAPI', '0006_datamodel_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamodel',
            old_name='uid',
            new_name='user',
        ),
    ]
